server {
  listen 9000;
  # 80にしておくとポートのことを考える必要がなくなる。

  server_name storage.local;

  # `localhost` はアプリのコンテナと被るので使えない。
  # server_name localhost;

  location / {
    proxy_pass http://storage:9000;

    proxy_set_header Host $http_host;
    # proxy_set_header Host $host;
    # `$host` だとポートを含まないことがある。

    # proxy_set_header X-Real-IP $remote_addr;
    # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # proxy_set_header X-Forwarded-Proto $scheme;

    # proxy_http_version 1.1;
    # proxy_set_header Connection "";
    # proxy_buffering off;
  }
}
